trailingComma: 'all'
semi: false
singleQuote: true
printWidth: 100
useTabs: false
parser: typescript
endOfLine: auto
jsxBracketSameLine: false
arrowParens: always
bracketSpacing: true
jsxSingleQuote: true
